add mpe config moving
AllenInstitute/np_workflows pull request #6
Opened 2024-03-12 21:34 UTC by mochic

Adds moving of mvr, sync, and camstim configs from their respective rigs to npexp_path for Dynamic Routing experiments.

2024-03-13 20:40 UTC, bjhardcastle requested changes

2024-03-13 20:40 UTC, bjhardcastle commented on pyproject.toml
pdm.lock should be updated too (`pdm lock` or `pdm update`) 

If you don't have everything set up I can do it

2024-03-13 20:40 UTC, bjhardcastle commented on src/np_workflows/shared/base_experiments.py
- I think we might actually want this in the `WithSession` class - it should work on all rigs right?
- it should happen before `copy_ephys()` (which takes a long time: it's good to see if small files copied immediately. then leave ephys copying overnight)

2024-03-14 21:37 UTC, mochic commented on src/np_workflows/shared/base_experiments.py
Resolved in [7f7805c](https://github.com/AllenInstitute/np_workflows/pull/6/commits/7f7805cbd827c28174c18dc57f8c59dbb270b0ed)

2024-03-25 23:05 UTC, merged